package org.golarion.model.spell;

import lombok.Getter;

public enum Subdomain implements Domain
{
    FIUMI("Fiumi"),
    GHIACCIO("Ghiaccio"),
    OCEANI("Oceani"),
    PIUMA("Piuma"),
    PELLICCIA("Pelliccia"),
    NUBI("Nubi"),
    VENTO("Vento"),
    COSTRUTTO("Costrutto"),
    FATICA("Fatica"),
    AGATHION("Agathion"),
    ARCONTI("Arconti"),
    AZATA("Azata"),
    AMICIZIA("Amicizia"),
    DEMONI("Demoni"),
    PROTEAN("Protean"),
    CAPRICCIO("Capriccio"),
    AMORE("Amore"),
    LUSSURIA("Lussuria"),
    CASA("Casa"),
    FAMIGLIA("Famiglia"),
    MEMORIA("Memoria"),
    PENSIERO("Pensiero"),
    CATASTROFE("Catastrofe"),
    IRA("Ira"),
    ALIENAZIONE("Alienazione"),
    INCUBO("Incubo"),
    FATO("Fato"),
    MALEDIZIONE("Maledizione"),
    FEROCIA("Ferocia"),
    RISOLUTEZZA("Risolutezza"),
    CENERE("Cenere"),
    FUMO("Fumo"),
    EROISMO("Eroismo"),
    ONORE("Onore"),
    RESURREZIONE("Resurrezione"),
    RISANAMENTO("Risanamento"),
    SANGUE("Sangue"),
    TATTICHE("Tattiche"),
    FURTO("Furto"),
    SOTTERFUGIO("Sotterfugio"),
    DIAVOLI("Diavoli"),
    INEVITABILI("Inevitabili"),
    LEALTA("Lealta"),
    LIBERAZIONE("Liberazione"),
    RIVOLUZIONE("Rivoluzione"),
    ARCANO("Arcano"),
    DIVINO("Divino"),
    DAEMON("Daemon"),
    ASSASSINIO("Assassinio"),
    NON_MORTE("Non Morte"),
    AUTORITA("Autorita"),
    MARTIRIO("Martirio"),
    LUNA("Luna"),
    NOTTE("Notte"),
    PERDITA("Perdita"),
    DIFESA("Difesa"),
    PUREZZA("Purezza"),
    ANIME("Anime"),
    ANTENATI("Antenati"),
    INTERDIZIONI("Interdizioni"),
    LINGUAGGIO("Linguaggio"),
    GIORNO("Giorno"),
    LUCE("Luce"),
    STAGIONI("Stagioni"),
    TEMPESTE("Tempeste"),
    CAVERNE("Caverne"),
    METALLO("Metallo"),
    CRESCITA("Crescita"),
    DECOMPOSIZIONE("Decomposizione"),
    COMMERCIO("Commercio"),
    ESPLORAZIONE("Esplorazione"),
    ARAZZO_OSCURO("Arazzo Oscuro"),
    ISOLAMENTO("Isolamento"),
    STELLE("Stelle");

    @Getter
    private final String name;

    Subdomain(String name)
    {
        this.name = name;
    }
}
