[versions]
javafx = "21"
lombok = "1.18.38"
jlink = "3.1.2"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
javafx = { id = "org.openjfx.javafxplugin", version = "0.1.0" }
jlink = { id = "org.beryx.jlink", version.ref = "jlink" }
