/*
 * This source file was generated by the Gradle 'init' task
 */
package org.golarion;

import javafx.application.Application;
import javafx.stage.Stage;
import org.golarion.view.DisplayMan;
import org.golarion.view.roots.Roots;

import java.util.logging.Logger;

public class App extends Application
{
    public static final Logger logger = Logger.getLogger(App.class.getName());

    public static void main(String[] args)
    {
        logger.info("Starting Golarion Helper");

        launch(args);
//        System.exit(0);
    }

    @Override
    public void start(Stage stage)
    {
        stage.setTitle("Golarion Helper");
        DisplayMan.Builder.setWindow(stage);
        DisplayMan.getInstance().display(Roots.MAIN_MENU);

        DisplayMan.getInstance().show();
    }
}
